config/routes.rb
RailsObjectsSample::Application.routes.draw do

  root :to => "pages#home"

  resources :posts, only: [:show]
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title

  validates :content, :title, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :email, :name

  validates :name, :email, presence: true
  validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ },
                    uniqueness: true

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @posts = Post.order('created_at DESC').all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "pt"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "keywords", :content => ""}
    %meta{:name => "description", :content => ""}

    %title= yield(:title) + "Titulo aqui"

    %link{:href => "/favicon.ico", :rel => "shortcut icon"}
    = yield(:header_tags)

    = stylesheet_link_tag "application", :type => nil, :media => "all"
    = javascript_include_tag "application", :type => nil
    = csrf_meta_tags

    /[if lt IE 9]
      %script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}

    :plain
      <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'XXXXX-XXXX']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

      </script>

  %body{:id => controller.controller_name}
    #wrap
      %header
        #masthead
          /- if current_user
          /  %p
          /    = "Bem-vindo <strong>#{current_user.name}</strong> &bull; ".html_safe
          /    = link_to "Sair", logout_path
          /- else
          /  %p
          /    = link_to "Acesse com Facebook", "/auth/facebook", :id => "facebook-connect"

        #logo<
          = link_to "Logo", root_url

        - if notice
          %p.notice
            = notice
        - if alert
          %p.alert
            = alert

      %hr
      #container
        %section{:role => "main"}
          = yield

        - if content_for?(:sidebar)
          %aside
            = yield(:sidebar)
      %hr
      %footer
        %p
          = "Copyright &copy; 2012 App".html_safe

app/views/pages/home.html.haml
%h2
  Posts

- if @posts.any?
  %ul
    - @posts.each do |post|
      %li
        = link_to(post.title, post_path(post))
- else
  %p
    Sem posts no momento =/

app/views/posts/show.html.haml
%h1
  = @post.title

#post-content
  = @post.content

#meta
  %p
    Author:
    = @post.user.name